version: '3'

services:
  redis:
    container_name: hepindico_redis
    ports:
      - "6379:6379"
    image: redis:alpine
    networks:
      net:
        aliases:
          - redis_net
    restart: always
    volumes:
      - redis:/data
  postgres:
    container_name: hepindico_postgres
    ports:
      - "5432:5432"
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: hepindico
    networks:
      net:
        aliases:
          - postgres_net
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
volumes:
  postgres:
  redis:
networks:
  net:
    name: hepindico_net
